### ISSUE TITLE
Example Online Deployment

### ISSUE THREAD

**Issue by cwecht** [Hackathon2020/CoronaHackathon2020#61]
https://www.pythonanywhere.com/

**Comment by keroe** [comment]
App is now online at:
Grenzerfahrung.eu.pythonanywhere.com 
It needed some hotfixes to get it running, I'm not sure how to do it in a proper way.
Related #64 #63

**Comment by cwecht** [comment]
http://Grenzerfahrung.eu.pythonanywhere.com
