### ISSUE TITLE
Name of the countries is not changing accordingly to the selected language

### ISSUE THREAD

**Issue by keroe** [Hackathon2020/CoronaHackathon2020#70]

**Comment by cwecht** [comment]
Occures this, if you change the selected language after changing once to the crossings-screen?
If so, this is an caching issue as the language is selected by the server. In this case, a strong refresh of the page is needed.

**Comment by keroe** [comment]
If I set the language at the selection screen and then go to the next page, the language does not change. But if I go one page further and then back, the language changes.
But the language of the countries in the dropdown menu never change.
